# Generated by Django 6.0.4 on 2026-04-25 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='inventory.sala')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='inventory.status')),
            ],
        ),
    ]
